namespace CustomerManagement.Api.Models;

/// <summary>
/// Represents a product record stored in the database.
/// </summary>
public class Product
{
    /// <summary>The unique identifier generated by the database on insert.</summary>
    public int Id { get; set; }

    /// <summary>The product name.</summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>The product description.</summary>
    public string? Description { get; set; }

    /// <summary>The product price.</summary>
    public decimal Price { get; set; }
}
